# Generated by Django 5.2.17 on 2026-09-19 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_pinyin', models.BooleanField(default=True)),
                ('show_tones', models.BooleanField(default=True)),
                ('show_translation', models.BooleanField(default=True)),
                ('show_hints', models.BooleanField(default=True)),
                ('font_size', models.CharField(blank=True, default='', max_length=2)),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'настройки пользователя',
                'verbose_name_plural': 'настройки пользователей',
            },
        ),
    ]
