# Generated by Django 5.2.17 on 2026-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='pause_mode',
            field=models.CharField(default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='repeats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
