# Generated by Django 5.2.17 on 2026-09-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('voice', models.CharField(max_length=64)),
                ('source_text', models.TextField()),
                ('audio', models.FileField(upload_to='tts/%Y/%m/')),
                ('duration_ms', models.PositiveIntegerField()),
                ('timings', models.JSONField(default=list)),
                ('provider', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_hash', 'voice'], name='audio_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_hash', 'voice'), name='unique_sentence_audio')],
            },
        ),
    ]
