# Generated by Django 5.2.17 on 2026-09-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenceaudio',
            name='audio',
            field=models.FileField(max_length=200, upload_to='tts/%Y/%m/'),
        ),
    ]
