# Generated by Django 5.2.17 on 2026-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified', models.CharField(db_index=True, max_length=128)),
                ('traditional', models.CharField(blank=True, max_length=128)),
                ('pinyin', models.CharField(blank=True, max_length=256)),
                ('language', models.CharField(max_length=8)),
                ('source', models.CharField(max_length=32)),
                ('definitions', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'dictionary entries',
                'indexes': [models.Index(fields=['simplified', 'language'], name='dict_word_language_idx')],
                'constraints': [models.UniqueConstraint(fields=('simplified', 'pinyin', 'language', 'source'), name='unique_dictionary_entry')],
            },
        ),
    ]
