# Generated by Django 5.2.17 on 2026-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('target_language', models.CharField(max_length=8)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('provider', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_hash', 'target_language'], name='translation_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_hash', 'target_language'), name='unique_sentence_translation')],
            },
        ),
    ]
